language: node_js

jdk: openjdk8
node_js:
  - "12"

cache:
  directories:
    - $HOME/.m2
env:
  - SCRIPT=travis-backend-run.sh
  - SCRIPT=travis-backend-test.sh
  - SCRIPT=travis-frontend.sh

install:
  - npm install npm@latest @angular/cli -g

script:
  - ./.travis/$SCRIPT